name: Docker Build and test 
on:
 push:
  branch:
    - testing-pipeline

    jobs:
      build:
      runs-on: ubuntu-latest


      steps:
         - name: Checkout our repository
         uses: actions/checkout@v2

         - name: setup Node
         uses: actions/steup-node@v2
         with:
         node-version: '14'


         - name: Build the Docker Image 
         run: docker build- -t hamzaismael2/service-web-store-lab4:hamzaismael2/service-web-store-lab4 . 


         - NAME: log in to the ole Docker hub
           run: docker login -u ${{ secrets.DOCKERNAME_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN}} 


        - name : push the docker to that silly little dockerhub
          run: docker push hamzaismael2/service-web-store-lab4:hamzaismael2/service-web-store-lab4
